#!/bin/bash

# Internet Indicator for B860H v1/v2 Wrapper
# by Lutfa Ilham
# v1.0
# GPIO Founder REYRE

if [ "$(id -u)" != "0" ]; then
  echo "This script must be run as root" 1>&2
  exit 1
fi

SERVICE_NAME="Internet Indicator"

function loop() {
  count=0
  while true; do
    bledon -lan dis
    if curl -X "HEAD" --connect-timeout 3 -so /dev/null "http://bing.com"; then
      bledon -lan on
    else
      bledon -lan off
      count=$((count+1))
      sleep 5
    fi
    # Jika led merah sebanyak 2 kali, reconnect dan tunggu 10detik sebelum ke perintah 1
    if [ $count -ge 2 ]
    then
      modpesrakitan
      sleep 10
      count=0
    fi
    sleep 2
  done
}

function start() {
  echo -e "Starting ${SERVICE_NAME} service ..."
  screen -AmdS internet-indicator "${0}" -l
}

function stop() {
  echo -e "Stopping ${SERVICE_NAME} service ..."
  kill $(screen -list | grep internet-indicator | awk -F '[.]' {'print $1'})
}

function usage() {
  cat <<EOF
Usage:
  -r  Run ${SERVICE_NAME} service
  -s  Stop ${SERVICE_NAME} service
EOF
}

case "${1}" in
  -l)
    loop
    ;;
  -r)
    start
    ;;
  -s)
    stop
    ;;
  *)
    usage
    ;;
esac
